kind: ReplicationController
apiVersion: v1
metadata:
  name: demo-client
  labels:
    name: demo-client
spec:
  replicas: 1
  selector:
    name: demo-client
  template:
    metadata:
      labels:
        name: demo-client
    spec:
      containers:
      - name: demo-client
        image: mickburgs/demo-client-service
        env:
        - name: URL_TO_TAR
          value: https://mxt-jenkins01.newyse.maxxton/view/ms%20acc/job/build-employee-service-acceptance/ws/build/distributions/employee-service.tar
        ports:
        - containerPort: 8111
          hostPort: 8111

